/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package EUAN;

import javax.swing.JOptionPane;

public class App {
  

    public static void main(String[] args) {
int anInt = 12;
short aShort = 12;
long along = 12;
byte aByte = 12;
System.out.println(" An int is " + anInt);
System.out.println("A short is " + aShort);
System.out.println("A long is " + along);
System.out.println("A byte is " + aByte);
 }
}